/**
 * prototype3 用の設定パラメータ一元管理モジュール
 */
export const CONFIG = {
	// 解像度と描画設定
	BASE_HEIGHT: 640,
	NUM_BLOBS: 14,
	TARGET_FPS: 30,

	// アメーバの物理パラメータ
	AMOEBA: {
		MIN_RADIUS: 18,
		MAX_RADIUS_ADD: 32,
		WANDER_DRIFT: 0.004,
		WANDER_ANGLE_CHANGE: 0.05,
		MIN_SPEED: 0.02,
		MAX_SPEED: 0.16,
		DEFAULT_FRICTION: 0.965,
		FUSION_EXPANSION_RATE: 0.30,
		FUSION_RANGE_MULTIPLIER: 1.5,
		WALL_AVOID_FORCE: 0.008,
		WALL_EDGE_BUFFER: 35,
		PULSE_SPEED_MIN: 0.006,
		PULSE_SPEED_MAX: 0.014
	},

	// ポインター（タッチ）物理
	POINTER: {
		RADIUS: 28,
		PULL_RANGE_MULTIPLIER: 3.0,
		PULL_FORCE: 0.22,
		MAX_FRICTION_DECREASE: 0.24,
		EXPAND_EASING: 0.10,
		SHRINK_EASING: 0.08
	},

	// 指を離したあとの力場物理
	FORCE_FIELD: {
		VELOCITY_INHERITANCE: 0.3,
		DECAY: 0.010,         // 物理的寿命の減衰速度
		VISUAL_DECAY: 0.015,  // 視覚的寿命の減衰速度
		PULL_STRENGTH: 0.025,
		FLOW_STRENGTH: 0.006,
		INITIAL_RADIUS: 65,
		MAX_RADIUS: 110,
		RADIUS_GROWTH: 0.015,
		INITIAL_VISUAL_RADIUS: 18,
		MAX_VISUAL_RADIUS: 80,
		VISUAL_RADIUS_GROWTH: 0.04
	}
};
